import type { AuthorProfile } from './narrativeTypes';

export const AUTHOR_CATALOG: AuthorProfile[] = [
  {
    id: 'a_degen_01',
    name: 'Kasia',
    handle: 'kasiaDegen',
    avatar: 'A1',
    tone: 'degen',
    topics: ['launch', 'buy', 'chart', 'meta'],
    riskLevel: 0.92,
    vocab: {
      hype: ['send it', 'moon setup', 'bag secured', 'squeeze'],
      caution: ['size down', 'do not marry this', 'respect exits'],
      slang: ['gm', 'ngmi', 'ape', 'degen'],
    },
  },
  {
    id: 'a_analyst_01',
    name: 'Marek',
    handle: 'mcapMechanic',
    avatar: 'A2',
    tone: 'analyst',
    topics: ['launch', 'buy', 'sell', 'migration', 'chart'],
    riskLevel: 0.34,
    vocab: {
      hype: ['breakout', 'trend shift', 'velocity rising', 'flow confirms'],
      caution: ['thin liquidity', 'distribution risk', 'mean reversion'],
      slang: ['tape', 'r:r', 'vwap', 'flow'],
    },
  },
  {
    id: 'a_skeptic_01',
    name: 'Ola',
    handle: 'rugRadar',
    avatar: 'A3',
    tone: 'skeptic',
    topics: ['sell', 'rug', 'migration', 'meta'],
    riskLevel: 0.12,
    vocab: {
      hype: ['maybe', 'if it holds'],
      caution: ['this smells off', 'watch exits', 'unlock risk'],
      slang: ['dev wallet', 'farm', 'honeypot'],
    },
  },
  {
    id: 'a_sniper_01',
    name: 'Nox',
    handle: 'entrySniper',
    avatar: 'A4',
    tone: 'sniper',
    topics: ['buy', 'sell', 'chart', 'meta'],
    riskLevel: 0.65,
    vocab: {
      hype: ['clean entry', 'momentum caught', 'timed it'],
      caution: ['late chase', 'bad fill', 'wait retest'],
      slang: ['entry', 'scalp', 'flip', 'tp'],
    },
  },
  {
    id: 'a_builder_01',
    name: 'Rafi',
    handle: 'builderTape',
    avatar: 'A5',
    tone: 'builder',
    topics: ['launch', 'migration', 'meta', 'buy'],
    riskLevel: 0.42,
    vocab: {
      hype: ['shipping', 'community strength', 'steady build'],
      caution: ['slow rollout', 'too early', 'wait for proof'],
      slang: ['infra', 'stack', 'rollout', 'shipping'],
    },
  },
  {
    id: 'a_news_01',
    name: 'Mina',
    handle: 'terminalWire',
    avatar: 'A6',
    tone: 'news',
    topics: ['launch', 'buy', 'sell', 'migration', 'rug'],
    riskLevel: 0.2,
    vocab: {
      hype: ['headline move', 'breaking flow', 'attention spike'],
      caution: ['unconfirmed', 'monitoring', 'awaiting follow-through'],
      slang: ['update', 'wire', 'alert', 'signal'],
    },
  },
  {
    id: 'a_degen_02',
    name: 'Jaro',
    handle: 'bagRunner',
    avatar: 'A7',
    tone: 'degen',
    topics: ['launch', 'buy', 'sell', 'meta'],
    riskLevel: 0.88,
    vocab: {
      hype: ['parabolic', 'full send', 'rocket leg'],
      caution: ['do not overstay', 'fake breakout', 'paper hands'],
      slang: ['frens', 'pump', 'stacking', 'fomo'],
    },
  },
  {
    id: 'a_analyst_02',
    name: 'Iga',
    handle: 'rangeDoctor',
    avatar: 'A8',
    tone: 'analyst',
    topics: ['buy', 'sell', 'chart', 'migration'],
    riskLevel: 0.28,
    vocab: {
      hype: ['range reclaim', 'structure improved', 'buyers in control'],
      caution: ['failed reclaim', 'seller pressure', 'fade risk'],
      slang: ['structure', 'volume', 'range', 'impulse'],
    },
  },
  {
    id: 'a_skeptic_02',
    name: 'Lena',
    handle: 'exitFirst',
    avatar: 'A9',
    tone: 'skeptic',
    topics: ['sell', 'rug', 'meta'],
    riskLevel: 0.1,
    vocab: {
      hype: ['keep it small', 'if setup confirms'],
      caution: ['protect capital', 'exit beats hope', 'liquidity trap'],
      slang: ['risk', 'unwind', 'trap', 'dump'],
    },
  },
  {
    id: 'a_sniper_02',
    name: 'Vex',
    handle: 'microSnipes',
    avatar: 'A10',
    tone: 'sniper',
    topics: ['buy', 'sell', 'chart'],
    riskLevel: 0.7,
    vocab: {
      hype: ['sniped base', 'caught breakout', 'good rotation'],
      caution: ['bad timing', 'spread too wide', 'skip this one'],
      slang: ['fill', 'timing', 'rotation', 'tap in'],
    },
  },
  {
    id: 'a_builder_02',
    name: 'Tomo',
    handle: 'shipAndHold',
    avatar: 'A11',
    tone: 'builder',
    topics: ['launch', 'migration', 'meta'],
    riskLevel: 0.36,
    vocab: {
      hype: ['foundation strong', 'next phase live', 'builders present'],
      caution: ['shipping risk', 'coordination lag', 'watch execution'],
      slang: ['phase', 'pipeline', 'stack', 'delivery'],
    },
  },
  {
    id: 'a_news_02',
    name: 'Kiro',
    handle: 'alphaDesk',
    avatar: 'A12',
    tone: 'news',
    topics: ['launch', 'buy', 'sell', 'migration', 'rug', 'meta'],
    riskLevel: 0.23,
    vocab: {
      hype: ['alpha spike', 'flow watch', 'signal confirmed'],
      caution: ['noise elevated', 'no confirmation yet', 'mixed signals'],
      slang: ['desk', 'wire', 'signal', 'monitor'],
    },
  },
];

export const AUTHORS_BY_ID = new Map(AUTHOR_CATALOG.map((a) => [a.id, a] as const));
